# Add file paths for your city boundary, origin blocks, and destinations. Enter False in all fields if data already exists on the SQL database
set_up:
  # for US cities use 4269, NZ cities use 4326, otherwise use whatever the origin blocks has been projected in
  projection: 4326
  # Use a seperate file for each dest type, use the same order as 'services' below
  destination_file_directory:
    - /homedirs/encn493/urban-optim/data/christchurch/clipped/schools.shp
    - /homedirs/encn493/urban-optim/data/christchurch/clipped/parks.shp
    - /homedirs/encn493/urban-optim/data/christchurch/clipped/malls.shp
  origin_file_directory: /homedirs/encn493/urban-optim/data/christchurch/raw/census-dwellings.shp

# Which services do you want to evalaute? (must match 'dest_type' name from destination matix | UNLESS making new destinations) TYPE: lst of str's
services:
  - schools
  - parks
  - malls

# What mode of transport are you evaluating? ['driving', 'walking', 'cycling'] TYPE: str
transport_mode: driving

# What metric would you like to evaluate? comment one out, leaving in list TYPE: str
metric:
  - distance
  # - duration

# What percent of CPU cores would you like to utilise? [0.0 - 1.0] TYPE: float
par_frac: 0.9

# What name would save the distance matrix as? TYPE: str
SQL:
  create_db: True
  database_name: access_nz # this
  table_name: distances_1 # this is the name for the table of distances
  port: '5001'
  host: 132.181.102.2


location:
    city: Christchurch
    city_code: ch
    # State code (e.g. 'wa' for Washington, Seattle), this selects the SQL database, 'access_{state}' TYPE: str
    state: nz
    country: new-zealand

# For logging information and downloading the latest OSM data (Check continent/country/state for the osm.pbf download link from https://download.geofabrik.de/north-america/us.html) TYPE: str
OSM:
    #http://download.geofabrik.de/australia-oceania/new-zealand-latest.osm.pbf
    state: new-zealand
    country: new-zealand
    continent: australia-oceania
    # where do you want your OSM data saved
    data_directory: /homedirs/encn493/urban-optim/data/christchurch/raw

OSRM:
    host: http://localhost
    port: '6010'
    # Do you want the port closed after use? [True, False] TYPE: bool
    shutdown: True
