# # Do you want to query access or setup the destination table? ['query', 'setup', 'both'] TYPE: str
# script_mode: query

# Add file paths for your city boundary, origin blocks, and destinations. Enter False if data already exists on the SQL database
set_up:
  # for US cities use 4269, NZ cities use 4326, otherwise use whatever the origin blocks has been projected in
  projection: 4269
  # ['False', 'shp', 'csv']
  destination_file_type: shp
  # Use a seperate file for each dest type, use the same order as 'services' below
  destination_file_directory:
    - /homedirs/man112/test/supermarket.shp
    - /homedirs/man112/test/library.shp
  origin_directory: False
  city_boundary_directory: False

# Which services do you want to evalaute? (must match 'dest_type' name from destination matix, unless script_mode='setup') TYPE: lst of str's
services:
  - supermarket
  - library

# What mode of transport are you evaluating? ['driving', 'walking', 'cycling'] TYPE: str
transport_mode: driving

# What metric would you like to evaluate? comment one out, leaving in list TYPE: str
metric:
  - distance
  - duration

# What percent of CPU cores would you like to utilise? [0.0 - 1.0] TYPE: float
par_frac: 0.9

# What name would save the distance matrix as? TYPE: str
SQL:
  table_name: nov_test
  port: '5001'
  host: 132.181.102.2


location:
    city: Seattle
    city_code: sea
    # State code (e.g. 'wa' for Washington, Seattle), this selects the SQL database, 'access_{state}' TYPE: str
    state: wa
    country: us

# For logging information and downloading the latest OSM data (Check continent/country/state for the osm.pbf download link from https://download.geofabrik.de/north-america/us.html) TYPE: str
OSM:
    state: washington
    country: us
    continent: north-america
    # where do you want your OSM data saved
    data_directory: /homedirs/tml62/osm

OSRM:
    host: http://localhost
    port: '6010'
    # Do you want the port closed after use? [True, False] TYPE: bool
    shutdown: True
